# Jekyll configuration

name: DucDigital - Duc.io
description: DucDigital tech blog
author: DucDigital

# url is currently only used only for the RSS feed in feed.xml
url: http://duc.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-58105711-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'ducio'
comments: true
permalink: /:categories/:year/:month/:title

paginate: 3
paginate_path: "/page/:num/"

related_posts_max: 5

markdown: redcarpet
highlighter: pygments
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

  # Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :compressed # You might prefer to minify using :compressed

defaults:
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'pages'
    values:
      layout: 'home'
      tags: []
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'posts'
      category: 'general'
      tags: []
  -
    scope:
      path: '' # an empty string here means all files in the project
      type: 'drafts'
    values:
      layout: 'posts'
      category: 'general'
      tags: []
